fun main() {
    println("enter student enrollment number")
    var a = readLine()
    println("enter student name")
    var b = readLine()
    println("enter student branch")
    var c = readLine()
    println("enter student class")
    var d = readLine()
    println("enter student batch")
    var e = readLine()
    println("enter student college name")
    var f = readLine()
    println("enter student university name")
    var g = readLine()
    println("enter student age")
    var h = readLine()
    println("$a")
    println("$b")
    println("$c")
    println("$d")
    println("$e")
    println("$f")
    println("$g")
    println("$h")
}
