fun main() {
    println("enter student enrollment number")
    var a = readLine()
    println("enter student name")
    var b = readLine()
    println("enter student branch")
    var c = readLine()
    println("enter student class")
    var d = readLine()
    println("enter student batch")
    var e = readLine()
    println("enter student college name")
    var f = readLine()
    println("enter student university name")
    var g = readLine()
    println("enter student age")
    var h = readLine()
    println("enrollment number:$a")
    println("name:$b")
    println("branch:$c")
    println("class:$d")
    println("batch:$e")
    println("college name:$f")
    println("university name:$g")
    println("age:$h")
}
